name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {GOOS: linux, GOARCH: amd64}
          - {GOOS: linux, GOARCH: arm, GOARM: 6}
          - {GOOS: linux, GOARCH: arm64}
          - {GOOS: darwin, GOARCH: amd64}
          - {GOOS: darwin, GOARCH: arm64}
          - {GOOS: windows, GOARCH: amd64}
          - {GOOS: freebsd, GOARCH: amd64}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./cmd/...

    - name: Test
      run: go test -v ./...

    - name: Test E2E
      run: |
        export GOBIN="$HOME/.local/bin/"
        go install github.com/rogpeppe/go-internal/cmd/testscript@v1.12.0
        go install filippo.io/age/cmd/...@latest
        cp age-plugin-sss "$HOME/.local/bin/age-plugin-sss"
        testscript ./testdata/*.txt
